# Generated by Django 5.1.4 on 2025-01-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('testimonials', models.TextField()),
                ('picture', models.ImageField(upload_to='testimonials/')),
                ('rating', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='emp',
            name='Emp_mail',
        ),
        migrations.AlterField(
            model_name='emp',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='emp',
            name='emp_mail',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
